Feature/UI wallet
alexanderem49/simple-exchange pull request #17
Opened 2023-10-27 09:51 UTC by GrigoriGrigoryanBytepitch

2023-10-27 10:47 UTC, Jorge-Lopes approved these changes
LGTM

2023-10-27 11:13 UTC, Jorge-Lopes commented on ui/package.json
Strange, I didn't noticed before

2023-10-27 11:16 UTC, Jorge-Lopes commented on ui/package.json
Fixed

2023-10-27 11:27 UTC, alexanderem49 approved these changes
LGTM

2023-10-27 12:07 UTC, anilhelvaci requested changes

2023-10-27 12:07 UTC, anilhelvaci commented on ui/src/Trade/ExchangeInterface.jsx
> +  const [assetBrand, setAssetBrand] = useState('BLD');
I think this isn't up to date. Are you sure you pushed the latest version?

2023-10-27 12:07 UTC, anilhelvaci commented on ui/src/Trade/ExchangeInterface.jsx
> +  const [priceBrand, setPriceBrand] = useState('IST');
Ditto here

2023-10-27 12:07 UTC, anilhelvaci commented on ui/src/App.jsx
> +        {/*{hash === "#about" && <About />}*/}
Better to delete these I believe

2023-10-27 12:07 UTC, anilhelvaci commented on ui/src/utils/makeOrder.js
> +      snackBarUpdater('error', 'Offer with error');
Do we have a snackbar?

2023-10-27 12:07 UTC, anilhelvaci commented on ui/src/store/store.js
> +      notifierState: { open: true, severity, message }
I think this is for the snackbar. Do you think we should add it? @GrigoriGrigoryanBytepitch

2023-11-01 11:30 UTC, anilhelvaci commented on ui/src/store/store.js
> +      }
I see that we're still getting the price and asset brand by querying the denoms.

2023-11-01 11:35 UTC, anilhelvaci commented on ui/src/Trade/ExchangeInterface.jsx
> +  const [assetBrand, setAssetBrand] = useState('BLD');
Ditto

2023-11-01 11:38 UTC, anilhelvaci commented on ui/src/Trade/ExchangeInterface.jsx
> +  const [priceBrand, setPriceBrand] = useState('IST');
Ditto

2023-11-03 06:44 UTC, merged